name: Python URL CHECK

on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: '0 */10 * * *'
  watch:
   types: [started]
jobs:
  run-script:
    runs-on: ubuntu:20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_PAT }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1 # 或你想要使用的Python版本

    - name: Install dependencies
      run: |
        pip install requests
        pip install bs4
        pip install pandas
    - name: Run script
      run: python test.py # 替换为你的脚本路径和名称

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --global url."https://x-access-token:${{ secrets.REPO_PAT }}@github.com/".insteadOf "https://github.com/"

    - name: Commit and Push
      run: |
        git add -A
        git commit -m "Add generated file" || echo "No changes to commit"
        git push
